# Utiliser l'image officielle de Node.js comme image de base
FROM node:22

# Créer et définir le répertoire de travail
WORKDIR /app

# Copier uniquement les fichiers package.json et package-lock.json
# pour installer les dépendances en premier
COPY package.json package-lock.json ./

# Installer les dépendances de l'application
RUN npm cache clean --force &&\
    npm ci &&\
    npm update &&\
    npm rebuild bcrypt --build-from-source

