version: '3.8'

services:
  backend:
    build:
      context: ./backend_ecommerce/backend_ecommerce
    container_name: backend
    ports:
      - "9090:9090"
    # volumes:
    #   - ./backend_ecommerce/backend_ecommerce:/server
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DIALECT=${DIALECT}
      - BACKEND_PORT=${BACKEND_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TOKEN=${TOKEN}

  frontend:
    build:
      context: ./frontend/my-app
    container_name: frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend/my-app:/app
    #   - node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # DB_PORT: ${DB_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8085:80"

volumes:
  mysql-data:
  node_modules:
