version: '3.8'

services:
  backend:
    build:
      context: ./backend_ecommerce/backend_ecommerce
    container_name: backend
    ports:
      - "9090:9090"
    volumes:
      - ./backend_ecommerce/backend_ecommerce:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DIALECT=${DIALECT}
      - BACKEND_PORT=${BACKEND_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TOKEN=${TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - WEB_APP_URL= http://localhost:3000
      - VITE_PUBLIC_KEY_STRIPE=${VITE_PUBLIC_KEY_STRIPE}
      - MY_EMAIL=${MY_EMAIL}
      - MY_PASSWORD=${MY_PASSWORD}
    networks:
      - jenkins_net  # Ajouter au même réseau

  frontend:
    build:
      context: ./frontend/my-app
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/my-app/src:/app/src
      - ./frontend/my-app/package.json:/app/package.json
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_PUBLIC_KEY_STRIPE=${VITE_PUBLIC_KEY_STRIPE}

    networks:
      - jenkins_net  # Ajouter au même réseau

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # DB_PORT: ${DB_PORT}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    depends_on:
      - phpmyadmin
    networks:
      - jenkins_net  # Ajouter au même réseau

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8085:80"
    networks:
      - jenkins_net  # Ajouter au même réseau

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx_logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - jenkins_net

  jenkins:
    image: custom-jenkins:latest
    container_name: jenkins
    restart: always
    user: root
    ports:
      - "8080:8080"  # Mappe le port 8080 pour accéder à Jenkins
      - "50000:50000" # Port pour les agents Jenkins
    volumes:
      - jenkins_data:/var/jenkins_home  # Volume persistant pour les données Jenkins
      - /var/run/docker.sock:/var/run/docker.sock  # Nécessaire pour que Jenkins puisse exécuter des conteneurs Docker
    environment:
      - JENKINS_OPTS=--prefix=/jenkins  # Optionnel : si vous voulez que Jenkins soit accessible via un sous-chemin (ex. : /jenkins)
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Désactive l'assistant de configuration initiale
    networks:
      - jenkins_net

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - postgresql
    ports:
      - "9000:9000"  # SonarQube interface web
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgresql:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - jenkins_net  # Ajouter au même réseau

  postgresql:
    image: postgres:latest
    hostname: postgresql
    container_name: postgresql
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_DB=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - postgresql:/var/lib/postgresql
    networks:
      - jenkins_net  # Ajouter au même réseau

  vault:
    image: hashicorp/vault:1.18
    container_name: vault
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"  # Token de root pour le mode développement (ne pas utiliser en production)
      VAULT_ADDR: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"  # Expose le port 8200 pour accéder à Vault
    command: "server -dev"  # Démarre Vault en mode développement
    volumes:
      - vault_data:/vault/file  # Utiliser le volume nommé pour stocker les données Vault

volumes:
  mysql-data:
  node_modules:
  sonarqube_data:
  sonarqube_temp:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql_data:
  postgresql:
  jenkins_data:
    driver: local
  vault_data:
    driver: local

networks:
  jenkins_net:
    driver: bridge